### PR TITLE
Adding initial specs

### PR DESCRIPTION
**Pull request by ryanwi**
Add initial set of specs.

### CODE REVIEW

**Comment by ryanwi** [comment]
LOL. Darn rabbitmq dependency. Will track that down.

**Comment by kyleries** [comment]
I added this if you can turn the actual publishing off: https://github.com/teamsnap/emque-producing/commit/c4d4f081ea0f40fe9e251f7cbc54d0506b13884d

**Comment by ryanwi** [comment]
Great, will see if I can pass that through.

**Comment by ryanwi** [comment]
Ok, that worked.

Now, to clean up this config, any suggestions for the config to avoid duplicating?

https://github.com/teamsnap/emque-stats/pull/4/files#diff-c1ef87f26aa057091b13783bd6b54752R4

Currently an app has do this, but a pass through of an emque::producing configuration object may be a cleaner option?

```
 Emque::Stats.configure do |config|
    config.app_name = "your_app"
    config.rabbitmq_options = { :url => "your rabbitmq url" }
    config.publish_messages = true
  end
```

**Comment by semmons99** [comment]
sounds like a usage of `class_eval`...I think.

**Comment by ryanwi** [comment]
@kyleries @semmons99 seemed like passing the config object through removed the duplication, and it also means that currently-producing apps don't have to do anything to use stats, I outlined that idea in the README. Configuration would only be necessary if you didn't produce already (i.e. the emque-consuming services)

**Comment by semmons99** [comment]
Looks good. I'd just remove the Gemfile.lock. That's usually not included with a gem.

**Comment by ryanwi** [comment]
great, just cleaned that up.

**Pull request merged**
